TAP_DANCE_ENABLE = yes
# RGBLIGHT_ENABLE = yes
# Only one Unicode method can be enabled
UCIS_ENABLE = no
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = yes

MOUSEKEY_ENABLE  = no
COMMAND_ENABLE   = no
MIDI_ENABLE = no